### ISSUE TITLE
做的好啊，实测小米14(houji) EU可以用。想请问一下是用什么解压的APP，我想把时钟日历什么的也拿过来

### ISSUE THREAD

**Issue by 2435043xia** [Simplxss/RecoverMipay#1]
RT

**Comment by Simplxss** [comment]
0. 从rom提取出来的App大部分都不是最新的, 实际上不如直接在应用商店下载.
1. 卡刷包用[payload-dumper-go](https://github.com/ssut/payload-dumper-go)解包; 线刷包先用simg2img转换格式, 然后用[lpunpack](https://github.com/unix3dgforce/lpunpack)提取分区文件.
2. Linux下挂载文件`mkdir product && mount product.img product`.
3. Do whatever you want to do.

**Comment by 2435043xia** [comment]
> 0. 从rom提取出来的App大部分都不是最新的, 实际上不如直接在应用商店下载.
> 1. 卡刷包用[payload-dumper-go](https://github.com/ssut/payload-dumper-go)解包; 线刷包先用simg2img转换格式, 然后用[lpunpack](https://github.com/unix3dgforce/lpunpack)提取分区文件.
> 2. Linux下挂载文件`mkdir product && mount product.img product`.
> 3. Do whatever you want to do.

我用卡刷包dump

> 0. 从rom提取出来的App大部分都不是最新的, 实际上不如直接在应用商店下载.
> 1. 卡刷包用[payload-dumper-go](https://github.com/ssut/payload-dumper-go)解包; 线刷包先用simg2img转换格式, 然后用[lpunpack](https://github.com/unix3dgforce/lpunpack)提取分区文件.
> 2. Linux下挂载文件`mkdir product && mount product.img product`.
> 3. Do whatever you want to do.

谢谢解答，你这应该也是用的eu。我是想从eu恢复功能来的。我下的稳定版系统解出来的img mount不上，有点苦恼。我再试试

**Comment by Simplxss** [comment]
我说的方法是通用的解包方式 据我所知目前小米并没有其他限制 我也不知道你具体是怎么操作的 但从描述来看多半是你哪里搞错了 自己检查吧
